name: Type labeler

on:
  pull_request:
    types:
      - opened

jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: add ✨ Feat label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'feat:') }}
        with:
          labels: ✨ Feat

      - name: add 🐞 Bug label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'fix:') }}
        with:
          labels: 🐞 Bug

      - name: add 🔨 Refactor label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'refactor:') }}
        with:
          labels: 🔨 Refactor

      - name: add 🎨 Style label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'style:') }}
        with:
          labels: 🎨 Style

      - name: add ⚙ Setting label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'chore:') }}
        with:
          labels: ⚙ Setting

      - name: add ✅ Test label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'test:') }}
        with:
          labels: ✅ Test

      - name: add 📝 Docs label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'docs:') }}
        with:
          labels: 📝 Docs
